[project]
name = "mod1_dockersql"
version = "0.1.0"
description = "este es un proyecto de inicio para crear aplicaciones en python"
readme = "README.md"
requires-python = ">=3.11"
dependencies = ["pandas", "sqlalchemy", "psycopg2", "pyarrow"]
